# Generated by Django 4.2.4 on 2023-09-06 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_articulo_alter_compra_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
    ]
