# Generated by Django 4.2.4 on 2023-09-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_alter_articulo_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Ilustración'),
        ),
    ]
