# Generated by Django 4.2.4 on 2023-09-10 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_itemcarrito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemcarrito',
            name='usuario',
        ),
    ]
