# Generated by Django 4.2.4 on 2023-09-17 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_categoria_articulo_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='categoria',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
