# Generated by Django 4.2.4 on 2023-09-17 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_alter_articulo_tipocategoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='tipoCategoria',
            field=models.CharField(choices=[('Computacion', 'Computación'), ('Componentes', 'Componentes'), ('Accesorios', 'Accesorios')], max_length=30),
        ),
    ]
