# Generated by Django 4.2.4 on 2023-09-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_alter_articulo_tipocategoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='tipoCategoria',
        ),
    ]
