# Generated by Django 4.2.4 on 2023-12-11 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0019_datosfacturacion_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Ilustración2'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Ilustración3'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='articulos', verbose_name='Ilustración4'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
