# Generated by Django 4.2.4 on 2023-12-15 00:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0020_articulo_image2_articulo_image3_articulo_image4_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.compra')),
                ('datosFacturacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miapp.datosfacturacion')),
            ],
        ),
    ]
